const BRAND_NAME_EN = {
  "나이키":         "Nike",
  "아디다스":       "Adidas",
  "슈프림":         "Supreme",
  "스투시":         "Stüssy",
  "칼하트":         "Carhartt",
  "뉴발란스":       "New Balance",
  "컨버스":         "Converse",
  "반스":           "Vans",
  "노스페이스":     "The North Face",
  "컬럼비아":       "Columbia",
  "닥터마틴":       "Dr. Martens",
  "팀버랜드":       "Timberland",
  "클락스":         "Clarks",
  "버켄스탁":       "Birkenstock",
  "아크테릭스":     "Arcteryx",
  "뉴에라":         "New Era",
  "디키즈":         "Dickies",
  "캉골":           "Kangol",
  "팔라스":         "Palace",
  "자라":           "Zara",
  "유니클로":       "UNIQLO",
  "에잇세컨즈":     "8 Seconds",
  "마뗑킴":         "Matin Kim",
  "미쏘":           "Mixxo",
  "스파오":         "SPAO",
  "크록스":         "Crocs",
  "코치":           "Coach",
  "마이클코어스":   "Michael Kors",
  "케이트스페이드": "Kate Spade",
  "롱샴":           "Longchamp",
  "만다리나덕":     "Mandarina Duck",
  "리바이스":       "Levi's",
  "타미힐피거":     "Tommy Hilfiger",
  "캘빈클라인":     "Calvin Klein",
  "게스":           "Guess",
  "빈폴":           "Beanpole",
  "애플":           "Apple",
  "삼성":           "Samsung",
  "소니":           "Sony",
  "캐논":           "Canon",
  "니콘":           "Nikon",
  "비비안웨스트우드": "Vivienne Westwood",
  "스와로브스키":   "Swarovski",
  "세이코":         "Seiko",
  "시티즌":         "Citizen",
  "꼼데가르송":     "Comme des Garçons",
  "디젤":           "Diesel",
  "히스테릭글래머": "Hysteric Glamour",
  "무신사스탠다드": "Musinsa Standard",
  "고야드":         "Goyard",
  "구찌":           "Gucci",
  "에르메스":       "Hermes",
  "보테가베네타":   "Bottega Veneta",
  "프라다":         "Prada",
  "버버리":         "Burberry",
  "크리스찬디올":   "Christian Dior",
  "페라가모":       "Ferragamo",
  "샤넬":           "Chanel",
  "루이비통":       "Louis Vuitton",
  "몽블랑":         "Montblanc",
  "크롬하츠":       "Chrome Hearts",
};

export function toBrandNameEn(koreanName) {
  if (!koreanName) return koreanName;
  return BRAND_NAME_EN[koreanName] || koreanName;
}
